### ISSUE TITLE
Can you create a tag?

### ISSUE THREAD

**Issue by johnpancoast** [Raphhh/trex#4]
I just like the reflection callable but I don't want to require this package without locking to a version (whatever it is). In the meantime, I can do this in composer but it's not ideal.

```
"raphhh/trex": "dev-master#<most-recent-git-hash>"
```

**Comment by Raphhh** [comment]
sorry, it is in dev. so no tag is possible for now. 
I will try to separate this part of the code in an indepedent and stable project.

**Comment by shideon** [comment]
Thanks!

**Comment by Raphhh** [comment]
just for you: https://github.com/Raphhh/trex-reflection/releases
hope it will help you!
